name: draft-release

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build binaries
        uses: georgik/esp-idf-ci-action@latest
      - name: Archive binaries
        run: |
          zip --junk-paths binaries build/*.bin build/bootloader/*.bin build/partition_table/*.bin
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: binaries.zip
