name: draft-release

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build binaries
        uses: espressif/esp-idf-ci-action@v4.2.1
      - name: Archive binaries
        run: |
          mkdir binaries
          cp build/*.bin build/bootloader/*.bin build/partition_table/*.bin support/* binaries/
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: binaries.zip
